version: '3.8'

services:
  app-php:
    image: ghcr.io/florentingarnier/loto:latest
    volumes:
      - assets:/app/public/assets
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    restart: unless-stopped

  nginx:
    image: ghcr.io/florentingarnier/loto-nginx:latest
    ports:
      - "80:80"
    volumes:
      - assets:/app/public/assets:ro
    depends_on:
      - app-php
    restart: unless-stopped

volumes:
  assets:
